import json

items = [
    ("1. This is a picture taken at a park.", "이 사진은 공원에서 찍은 거야.", "디스 이즈 어 픽처 테이큰 애더 파크"),
    ("2. The first thing I can see in this picture is two women.", "사진에서 제일 먼저 눈에 들어오는 건 두 여성분이야.", "더 퍼스트 씽 아이 캔 씨 인 디스 픽처 이즈 투 위민"),
    ("3. In the foreground of the picture, I can see a fountain.", "사진 맨 앞쪽(전경)에는 분수대가 보여.", "인 더 포어그라운드 오브 더 픽처, 아이 캔 씨 어 파운튼"),
    ("4. In the middle of the picture, I can see a fountain.", "사진 한가운데 분수대가 있네.", "인 더 미돌 오브 더 픽처, 아이 캔 씨 어 파운튼"),
    ("5. In the background of the picture, I can see a fountain.", "사진 저 뒤쪽에 분수대가 보여.", "인 더 백그라운드 오브 더 픽처, 아이 캔 씨 어 파운튼"),
    ("6. On the left side of the picture, there is a sidewalk.", "사진 왼편에 인도(보도)가 깔려 있어.", "온 더 레프트 사이드 오브 더 픽처, 데어 이즈 어 사이드워크"),
    ("7. On the right side of the picture, there is a sidewalk.", "사진 오른쪽에 걸어 다니는 길(보도)이 보여.", "온 더 라이트 사이드 오브 더 픽처, 데어 이즈 어 사이드워크"),
    ("8. Next to her, there is another woman.", "그 여자 옆에 딴 여자가 한 명 더 있어.", "넥스트 투 허, 데어 이즈 어너더 위먼"),
    ("9. Behind her, I can see two men standing.", "그 여자 뒤로 남자 두 명이 서 있는 게 보여.", "비하인드 허, 아이 캔 씨 투 맨 스탠딩"),
    ("10. Most of them are wearing formal clothes.", "대부분 단정하게 정장을 차려입었네.", "모스트 오브 뎀 아 웨어링 포멀 클로즈"),
    ("11. Some of them are wearing casual clothes.", "몇몇은 편한 옷차림을 하고 있어.", "섬 오브 뎀 아 웨어링 캐주얼 클로즈"),
    ("12. She is looking at a menu.", "메뉴판 살펴보고 있어.", "쉬 이즈 루킹 애더 메뉴"),
    ("13. He is writing something down.", "뭐 열심히 메모(받아쓰기)하는 중이야.", "히 이즈 라이팅 섬씽 다운"),
    ("14. He is drinking water.", "물 마시고 있네.", "히 이즈 드링크잉 워더"),
    ("15. She is serving food to customers.", "손님들한테 음식을 챙겨드리고(서빙하고) 있어.", "쉬 이즈 서빙 푸드 투 커스토머스"),
    ("16. She is holding a cup.", "손에 컵을 쥐고 있네.", "쉬 이즈 홀딩 어 컵"),
    ("17. They are standing at the cashier.", "계산대 앞에 서 있어.", "데이 아 스탠딩 애더 캐시어"),
    ("18. They are having a conversation.", "둘이서 얘기 나누고 있네.", "데이 아 해빙 어 콘버스에이션"),
    ("19. She is looking into a bag.", "가방 속을 뒤적거리며(들여다)보고 있어.", "쉬 이즈 루킹 인투 어 백"),
    ("20. He is helping customers.", "손님 응대하는 중이야.", "히 이즈 헬핑 커스토머스"),
    ("21. They are sitting at a table.", "테이블에 둘러앉아 있네.", "데이 아 시팅 애더 테이블"),
    ("22. He is looking for something.", "뭐 찾느라 두리번거리고 있어.", "히 이즈 루킹 포 섬씽"),
    ("23. He is handing over a credit card.", "카드를 건네주고 있네.", "히 이즈 핸딩 오버 어 크레딧 카드"),
    ("24. He is pushing a cart.", "카트 밀고 가고 있어.", "히 이즈 푸싱 어 카트"),
    ("25. He is looking at a product.", "물건 구경(둘러보기)하는 중이야.", "히 이즈 루킹 애더 프로덕트"),
    ("26. They are waiting in line.", "줄 서서 순서 기다리고 있네.", "데이 아 웨이팅 인 라인"),
    ("27. They are arranging items.", "물건 진열 정돈하고 있어.", "데이 아 어레인지잉 아이템스"),
    ("28. She is holding a shopping bag.", "쇼핑백을 들고 가네.", "쉬 이즈 홀딩 어 쇼핑 백"),
    ("29. He is reaching for an item.", "손을 뻗어서 물건 집으려고 해.", "히 이즈 리칭 포 앤 아이템"),
    ("30. He is holding a plastic bag.", "비닐봉지를 들고 있네.", "히 이즈 홀딩 어 플라스틱 백"),
    ("31. He is raising his hand.", "손을 쩍 들고 있네.", "히 이즈 레이징 히즈 핸드"),
    ("32. She is holding a document.", "서류를 손에 쥐고 있네.", "쉬 이즈 홀딩 어 다큐먼트"),
    ("33. He is making a presentation.", "발표(프레젠테이션) 진행 중이야.", "히 이즈 메이킹 어 프레젠테이션"),
    ("34. He is using a tablet.", "태블릿 PC 조작하고 있네.", "히 이즈 유징 어 태블릿"),
    ("35. They are reading a document.", "같이 서류를 읽고 있어.", "데이 아 리딩 어 다큐먼트"),
    ("36. He is hanging his clothes on a rack.", "행어(옷걸이)에 옷 걸고 있어.", "히 이즈 행잉 히즈 클로즈 온 어 랙"),
    ("37. She is picking up a piece of paper.", "바닥에 떨어진 종이 한 장 줍고 있어.", "쉬 이즈 피킹 업 어 피스 오브 페이퍼"),
    ("38. There is a man taking a picture.", "어떤 남자가 사진 찍어주고 있네.", "데어 이즈 어 맨 테이킹 어 픽처"),
    ("39. She is walking a dog.", "강아지 산책시키는 중이야.", "쉬 이즈 워킹 어 독"),
    ("40. He is lying on the ground.", "바닥에 대자로 뻗어(누워) 있네.", "히 이즈 라이잉 온 더 그라운드"),
    ("41. She is pushing a baby stroller.", "유모차 끌고 가고 있어.", "쉬 이즈 푸싱 어 베이비 스트롤러"),
    ("42. He is riding a boat.", "보트 타고 있네.", "히 이즈 라이딩 어 보트"),
    ("43. He is loading a box into a truck.", "트럭에 상자 짐을 싣는 중이야.", "히 이즈 로딩 어 박스 인투 어 트럭"),
    ("44. He is relaxing on a beach chair.", "선베드에 누워서 힐링하고 있어.", "히 이즈 리랙싱 온 어 비치 체어"),
    ("45. They are walking down the stairs.", "계단 내려가는 중이야.", "데이 아 워킹 다운 더 스타즈"),
    ("46. They are crossing the street.", "길 건너고 있네.", "데이 아 크로싱 더 스트리트"),
    ("47. They are walking on the street.", "길거리를 거닐고 있어.", "데이 아 워킹 온 더 스트리트"),
    ("48. She is looking at a smartphone.", "폰 쳐다보고 있네.", "쉬 이즈 루킹 애더 스마트폰"),
    ("49. They are performing.", "공연/버스킹 하는 중이야.", "데이 아 퍼포밍"),
    ("50. It relieves my stress.", "그거 하면 스트레스가 확 풀려.", "잇 리리브스 마이 스트레스"),
    ("51. I'm stressed out these days, so I need it.", "요새 스트레스가 극에 달해서 이게 꼭 필요해.", "암 스트레스트 아웃 디즈 데이즈, 쏘 아이 니드 잇"),
    ("52. It's cheaper, so I can save money.", "이게 더 싸니까 지갑 사정을 지킬 수 있어.", "잇스 치퍼, 쏘 아이 캔 세이브 머니"),
    ("53. The price is reasonable.", "가격이 아주 착해.", "더 프라이스 이즈 리즈너블"),
    ("54. It's faster, so I can save time.", "시간 절약에는 이게 직빵이야.", "잇스 패스터, 쏘 아이 캔 세이브 타임"),
    ("55. I can get a lot of useful information from my friends.", "친구들한테 알짜배기 꿀팁을 많이 얻을 수 있어.", "아이 캔 겟 어 랏 오브 유스풀 인포메이션 프롬 마이 프렌즈"),
    ("56. It's more reliable, so the information is more trustworthy.", "출처가 확실해서(신뢰도가 높아서) 믿고 볼 만해.", "잇스 모어 리라이어블, 쏘 더 인포메이션 이즈 모어 트러스트워디"),
    ("57. I can get information anytime, anywhere on my smartphone.", "스마트폰만 있으면 언제 어디서든 손쉽게 정보를 찾아볼 수 있지.", "아이 캔 겟 인포메이션 에니타임, 에니웨어 온 마이 스마트폰"),
    ("58. It has great facilities.", "거기 부대시설이 장난 아니게 잘 되어 있어.", "잇 해즈 그레이트 퍼실리티스"),
    ("59. The place is popular, so people love it.", "거기 완전 핫플이라 사람들로 늘 붐벼.", "더 플레이스 이즈 파퓰러, 쏘 피플 러브 잇"),
    ("60. They are too old, so I think it's good to have new ones. They are outdated.", "너무 낡고 오래돼서 새 걸로 싹 바꾸는 게 맞아. 완전 구식이거든.", "데이 아 투 올드, 쏘 아이 씽크 잇스 굿 투 해브 뉴 원스. 데이 아 아웃데이티드"),
    ("61. If we had more stores here, it would be more convenient.", "동네에 매장이 좀 더 생기면 훨씬 살기 편해질 텐데.", "이프 위 해드 모어 스토어스 히어, 잇 우드 비 모어 컨비니언트"),
    ("62. I'm a worker, so my budget is tight.", "나 유리지갑 직장인이라 주머니 사정이 팍팍해.", "암 어 워커, 쏘 마이 버짓 이즈 타이트"),
    ("63. I can't afford to buy expensive things.", "비싼 건 쳐다볼 엄두도 못 내.", "아이 캔트 어포드 투 바이 익스펜시브 씽스"),
    ("64. I don't want to waste too much money on that.", "그런 데다 쓸데없이 쌩돈 쓰고 싶지 않아.", "아이 돈트 원트 투 웨이스트 투 머치 머니 온 댓"),
    ("65. It's a waste of money.", "완전 돈 지랄/낭비야.", "잇스 어 웨이스트 오브 머니"),
    ("66. I'm a worker, so I'm busy with my work.", "직장 생활하느라 눈코 뜰 새 없이 바빠.", "암 어 워커, 쏘 암 비지 위드 마이 워크"),
    ("67. I don't have much time.", "시간적 여유가 별로 없어.", "아이 돈트 해브 머치 타임"),
    ("68. I don't want to waste time on that.", "그런 일로 시간 허비하고 싶지 않아.", "아이 돈트 원트 투 웨이스트 타임 온 댓"),
    ("69. It's a waste of time.", "괜히 시간만 까먹는 일이야.", "잇스 어 웨이스트 오브 타임"),
    ("70. It's necessary for me.", "나한테는 선택이 아니라 필수야.", "잇스 네세서리 포 미"),
    ("71. I frequently use it.", "입에 달고 살듯이 애용해.", "아이 프릭퀀틀리 유즈 잇"),
    ("72. It makes me happy and I can have a great experience.", "기분 전환도 되고 특별한 추억도 만들 수 있어서 좋아.", "잇 메이크스 미 해피 앤드 아이 캔 해브 어 그레이트 익스피리언스"),
    ("73. They provide a good environment and a pleasant experience.", "쾌적한 환경을 제공해 줘서 머무는 내내 기분이 좋아.", "데이 프로바이드 어 굿 엔바이런먼트 앤드 어 플레전트 익스피리언스"),
    ("74. I like to try new things.", "난 호기심이 많아서 색다른 것에 도전해 보는 걸 좋아해.", "아이 라이크 투 트라이 뉴 씽스"),
    ("75. It's reliable, so I can trust the product.", "믿고 쓰는 브랜드라 품질은 두말할 필요도 없지.", "잇스 리라이어블, 쏘 아이 캔 트러스트 더 프로덕트"),
    ("76. It's a popular item, so people will love it.", "요즘 유행하는 대세템이라 선물하면 다들 뻑갈 걸.", "잇스 어 파퓰러 아이템, 쏘 피플 윌 러브 잇"),
    ("77. It has sentimental value.", "나한테는 추억과 애정이 깃든 물건이야.", "잇 해즈 센티멘탈 밸류"),
    ("78. It's a good gift.", "선물용으로 제격이야.", "잇스 어 굿 기프트"),
    ("79. It's part of my routine.", "내 하루 일과에서 빠질 수 없는 루틴이야.", "잇스 파트 오브 마이 루틴"),
    ("80. It's my habit.", "그냥 내 몸에 밴 습관이지 뭐.", "잇스 마이 해빗"),
    ("81. I really liked it.", "진짜 마음에 쏙 들었어!", "아-릴리-라이긷"),
    ("82. It was great.", "정말 끝내줬지.", "이워즈 그레잍"),
    ("83. It was awesome.", "완전 대박/짱이었어!", "이워저-썸"),
    ("84. It's cheaper and faster.", "이게 훨씬 가성비 좋고 빠르잖아.", "잍스 츼퍼런 패아스터"),
    ("85. It's very convenient and useful.","완전 꿀템에다 실용성 대박이야.", "잍스 붸리 컨븨년-너뉴-스ㅍ훠오"),
    ("86. It's very helpful to me.", "나한테 진짜 효자 노릇 확실히 해.", "잍스 붸리 헬ㅍ훨더미"),
    ("87. It's my favorite thing to do.", "내가 제일 환장하게 좋아하는 일이야.", "잍스 마이 페이브륏-씽더두"),
    ("88. It makes me happy, so I can forget about my worries.", "그거 하면 절로 신이 나서 근심 걱정이 싹 사라져.", "이메이스미 해피, 쏘와이컨 퍼게러바우마이 우워-릐즈"),
    ("89. It's more fun and entertaining, so I don't get bored.", "재미 요소가 풍부해서 심심할 겨를이 없어.", "잍스 모오ㄹ 퍼넌 에너뤠이닝, 쏘와이돈 게으보오ㄹㄷ"),
    ("90. I think it's more fun to do things in a group.", "혼자 노는 것보다 북적북적 모여서 해야 제맛이지.", "아이 씽크 잇스 모어 펀 투 두 씽스 인 어 그룹"),
    ("91. I can meet new people and make friends.", "새로운 인맥도 쌓고 사람들과 친해질 수 있잖아.", "아이 캔 미트 뉴 피플 앤드 메이크 프렌즈"),
    ("92. I feel more comfortable and I can focus better.", "마음이 한결 편안해지니까 집중도 쏙쏙 잘 돼.", "아이 필 모어 컴프터블 앤드 아이 캔 포커스 베터"),
    ("93. I don't have to waste time waiting for others.", "괜히 남 눈치 보며 약속 시간 축낼 필요도 없지.", "아이 돈트 해브 투 웨이스트 타임 웨이팅 포 어더스"),
    ("94. I feel more comfortable at home.", "역시 집 떠나면 고생이라고, 이불 속이 최고야.", "아이 필 모어 컴프터블 애트 홈"),
    ("95. I can save time because I don't have to waste time going out.", "굳이 밖으로 왔다 갔다 하는 동선을 줄일 수 있으니 시간 절약돼.", "아이 캔 세이브 타임 비코즈 아이 돈트 해브 투 웨이스트 타임 고잉 아웃"),
    ("96. It's more personal and builds a closer relationship.", "더 솔직하고 사적인 얘기를 트면서 급속도로 친해져.", "잇스 모어 퍼스널 앤드 빌즈 어 클로서 리레이션십"),
    ("97. It causes less misunderstanding.", "괜한 오해가 생길 여지를 줄여줘.", "잇 코지스 레스 미스언더스탠딩"),
    ("98. The conference will be held on June 20th at the Hilton Hotel.", "컨퍼런스는 6월 20일 힐튼 호텔에서 개최됩니다.", "더 콘퍼런스 윌 비 헬드 온 준 트웬티스 애트 더 힐튼 호텔"),
    ("99. It will start at 9 am.", "오전 9시 정각에 스타트합니다.", "잇 윌 스타트 애트 나인 에이엠"),
    ("100. The seminar will end at 5 pm.", "세미나는 오후 5시 마감 예정입니다.", "더 세미나 윌 엔드 애트 파이브 피엠"),
    ("101. No, I'm afraid that you have the wrong information.", "아, 유감스럽지만 잘못 알고 계신 내용입니다.", "노, 암 어프레이드 댓 유 해브 더 롱 인포메이션"),
    ("102. Actually, the registration and coffee session will start at 9 am in the lobby.", "사실 로비 명단 접수 및 다과 세션은 9시 시작입니다.", "액추얼리, 더 레지스트레이션 앤드 커피 세션 윌 스타트 애트 나인 에이엠 인 더 로비"),
    ("103. There are two sessions.", "세션은 2가지 트랙으로 나뉩니다.", "데어 아 투 세션스"),
    ("104. First, at 1 pm, there is a workshop on social media marketing by Ray Kingston.", "먼저 1시에는 레이 킹스턴 강사의 소셜 마케팅 워크숍이 준비되어 있고,", "퍼스트, 애트 원 피엠, 데어 이즈 어 워크숍 온 소셜 미디어 마케팅 바이 레이 킹스턴"),
    ("105. Next, at 2:30 pm, there is a discussion on appealing to sports fans through marketing by Kevin Delmont.", "이어서 2시 30분에는 케빈 델몬트 씨가 진행하는 스포츠 마케팅 토론회가 이어집니다.", "넥스트, 애트 투 서티 피엠, 데어 이즈 어 디스커션 온 어필링 투 스포츠 팬스 쓰루 마케팅 바이 케빈 델몬트"),
    ("106. You will depart from San Francisco at 10 am.", "샌프란시스코발 비행기는 오전 10시 출발입니다.", "유 윌 디파트 프롬 샌 프란시스코 애트 텐 에이엠"),
    ("107. You will arrive in Los Angeles at 3 pm.", "LA 현지 도착 시각은 오후 3시입니다.", "유 윌 어라이브 인 로스앤젤레스 애트 쓰리 피엠"),
    ("108. You will take Korean Air 105.", "대한항공 KE105편 탑승하시면 됩니다.", "유 윌 테이크 코리안 에어 원오파이브"),
    ("109. You will stay at Glen Hotel.", "숙소는 글렌 호텔로 픽스되어 있습니다.", "유 윌 스테이 애트 글렌 호텔"),
    ("110. You will have lunch. Lunch will be provided.", "점심 식사 스케줄이 포함되어 있으며, 식사는 제공됩니다.", "유 윌 해브 런치. 런치 윌 비 프로바이디드"),
    ("111. You will have dinner.", "저녁 식사 자리가 마련되어 있습니다.", "유 윌 해브 디너"),
    ("112. You will have a meeting.", "미팅 일정이 잡혀 있습니다.", "유 윌 해브 어 미팅"),
    ("113. You will give a speech.", "대표로 기조연설/축사를 해주셔야 합니다.", "유 윌 기브 어 스피치"),
    ("114. You will give a presentation.", "발표 순서가 준비되어 있습니다.", "유 윌 기브 어 프레젠테이션"),
    ("115. You will give a lecture.", "강연을 맡아서 진행해 주실 예정입니다.", "유 윌 기브 어 렉처"),
    ("116. There was supposed to be an interview, but it has been canceled.", "원래 면접 일정이 잡혀 있었는데 취소 처리되었습니다.", "데어 워즈 서포즈드 투 비 앤 인터뷰, 벗 잇 해즈 빈 캔슬드"),
    ("117. There was supposed to be a meeting, but it has been postponed.", "회의가 열릴 예정이었으나 뒤로 연기되었습니다.", "데어 워즈 서포즈드 투 비 어 미팅, 벗 잇 해즈 빈 포스트폰드"),
    ("118. There was supposed to be a meeting with Jane White at 2 pm on Tuesday, but it has been rescheduled to Friday.", "화요일 2시에 제인 화이트 씨와의 미팅이 있었는데 금요일로 일정이 변경(조율)되었습니다.", "데어 워즈 서포즈드 투 비 어 미팅 위드 제인 화이트 애트 투 피엠 온 튜즈데이, 벗 잇 해즈 빈 리스케줄드 투 프라이데이"),
    ("119. She got a master's degree in design from Vancouver Art University in 2010.", "그분 2010년에 밴쿠버 예술대 디자인 석사 과정을 마치셨어요.", "쉬 갓 어 마스터스 디그리 인 디자인 프롬 밴쿠버 아트 유니버시티 인 트웬티텐"),
    ("120. From 2015 to 2017, she worked at Jasper Fashion magazine as a director.", "2015년부터 2년 동안 재스퍼 패션 잡지사 디렉터로 몸담으셨고요.", "프롬 트웬티피프틴 투 트웬티세븐틴, 쉬 워크트 애트 재스퍼 패션 매거진 애즈 어 디렉터"),
    ("121. From 2017 up to now, she has worked at Toronto Fashion magazine as a chief editor.", "2017년부터 지금까지는 토론토 패션지 총괄 편집장으로 재직 중이십니다.", "프롬 트웬티세븐틴 업 투 나우, 쉬 해즈 워크트 애트 토론토 패션 매거진 애즈 어 치프 에디터"),
    ("122. I think she is qualified because...", "그분이 적임자(자격을 갖춘 인재)라고 단언하는 이유는...", "아이 씽크 쉬 이즈 퀄리파이드 비코즈"),
    ("123. He is fluent in Spanish.", "그 친구 스페인어 원어민 수준으로 구사해.", "히 이즈 플루언트 인 스패니시"),
    ("124. She is certified in Pilates.", "필라테스 정식 강사 자격증 소지자셔.", "쉬 이즈 서티파이드 인 필라테스"),
    ("125. He has experience in education.", "그분 교육 분야에서 뼈가 굵으신(경력이 풍부한) 분이야.", "히 해즈 익스피리언스 인 에듀케이션"),
    ("126. You will interview Jessica Anderson at 9 am.", "9시 정각에 제시카 앤더슨 씨 면접 진행해 주시면 됩니다.", "유 윌 인터뷰 제시카 앤더슨 애트 나인 에이엠"),
    ("127. You have an interview with John White from Eco Electronics who is applying for the marketing manager position.", "마케팅 팀장 자리에 지원하신 에코 일렉트로닉스의 존 화이트 씨와 인터뷰가 예정되어 있습니다.", "유 해브 앤 인터뷰 위드 존 화이트 프롬 에코 일렉트로닉스 후 이즈 어플라이잉 포 더 마케팅 매니저 포지션"),
    ("128. She has five years of experience.", "그 동네 짬밥(경력)만 5년 차 베테랑이야.", "쉬 해즈 파이브 이어스 오브 익스피리언스"),
    ("129. He is applying for the editor position.", "그 사람 에디터(편집자) 직무에 원서 넣었어.", "히 이즈 어플라이잉 포 더 에디터 포지션"),
    ("130. You have to pay $20 for the oil painting class.", "유화 클래스 수강료는 20달러 지불하셔야 합니다.", "유 해브 투 페이 트웬티 달러스 포 더 오일 페인팅 클래스"),
    ("131. It's $20.", "가격은 20달러입니다.", "잇스 트웬티 달러스"),
    ("132. You should register by January 3rd.", "1월 3일까지는 수강 접수를 마쳐주셔야 합니다.", "유 슈드 레지스터 바이 재뉴어리 서드"),
    ("133. If you are a member, it's $20.", "회원이시면 우대가 적용되어 20달러에 이용 가능하십니다.", "이프 유 아 어 멤버, 잇스 트웬티 달러스"),
    ("134. It's free of charge.", "공짜/무료 이용입니다.", "잇스 프리 오브 차지"),
    ("135. It's for members.", "회원 단독 혜택입니다.", "잇스 포 멤버스"),
    ("136. There is a cooking for beginners class.", "요린이(초보자)를 위한 쿠킹 클래스가 개설되어 있어요.", "데어 이즈 어 쿠킹 포 비기너스 클래스"),
    ("137. Sean Kim will teach the painting class.", "미술 반은 션 김 선생님이 전담 지도하십니다.", "션 김 윌 티치 더 페인팅 클래스"),
    ("138. There is a class on French art history.", "프랑스 미술사 강좌가 준비되어 있어요.", "데어 이즈 어 클래스 온 프렌치 아트 히스토리"),
    ("139. Jennifer Houston will teach a class on computer skills.", "컴활(컴퓨터 활용) 강좌는 제니퍼 휴스턴 강사가 맡습니다.", "제니퍼 휴스턴 윌 티치 어 클래스 온 컴퓨터 스킬스"),
    ("140. They can learn new things.", "새로운 지식과 기술을 스펀지처럼 흡수할 수 있죠.", "데이 캔 러닝 뉴 씽스"),
    ("141. They can meet new people and expand their network.", "다양한 사람들을 만나며 인맥 스펙트럼을 넓힐 수 있죠.", "데이 캔 미트 뉴 피플 앤드 익스팬드 데어 네트워크"),
    ("142. They can have a lot of new experiences and broaden their perspective.", "다채로운 경험을 통해 시야와 세상을 보는 안목이 넓어져요.", "데이 캔 해브 어 랏 오브 뉴 익스피리언시스 앤드 브로드너 데어 퍼스펙티브"),
    ("143. They can't make good decisions because they are not mature enough.", "아직 혈기만 왕성하고 철이 안 들어서 합리적인 판단을 못 내려요.", "데이 캔트 메이크 굿 디시전스 비코즈 데이 아 낫 매추어 이너프"),
    ("144. They will be distracted.", "한눈팔거나 집중력이 흐트러지기 십상이죠.", "데이 윌 비 디스트랙티드"),
    ("145. They can't focus on their work.", "손에 일이 안 잡혀서 딴짓하게 돼요.", "데이 캔트 포커스 온 데어 워크"),
    ("146. They can't get good results at work.", "업무에서 좋은 성과를 낼 리 만무하죠.", "데이 캔트 겟 굿 리절츠 애트 워크"),
    ("147. They will fall behind at work.", "직장에서 도태되거나 뒤처지기 십상이에요.", "데이 윌 폴 비하인드 애트 워크"),
    ("148. They can't work efficiently.", "일 능률이 당통 오르지 않죠.", "데이 캔트 워크 이피션틀리"),
    ("149. They can save money.", "주머니 사정을 지키고(돈을 절약하고) 알뜰하게 살 수 있어요.", "데이 캔 세이브 머니"),
    ("150. The cost of living is too high.", "요즘 장바구니/생활 물가가 미친 듯이 올랐어요.", "더 코스트 오브 리빙 이즈 투 하이"),
    ("151. They can't make a living.", "입에 풀칠하기도 팍팍한 실정이에요.", "데이 캔트 메이크 어 리빙"),
    ("152. I can get a high salary.", "연봉을 빵빵하게(높게) 받을 수 있어요.", "아이 캔 겟 어 하이 샐러리"),
    ("153. I can get a higher salary.","몸값을 높여서 더 높은 연봉을 챙길 수 있죠.", "아이 캔 겟 어 하이어 샐러리"),
    ("154. That's a good investment because it makes lives better.", "삶의 질을 대폭 높여주니 절대 돈 아깝지 않은 투자예요.", "댓스 어 굿 인베스트먼트 비코즈 잇 메이크스 라이브스 베터"),
    ("155. They can focus better.", "업무나 공부에 훨씬 몰입하기 쉬워요.", "데이 캔 포커스 베터"),
    ("156. They will not be distracted by others.", "남들 때문에 산만해지거나 페이스를 잃지 않아요.", "데이 윌 낫 비 디스트랙티드 바이 어더스"),
    ("157. They can set their own schedule.", "스스로 자기 주도적으로 일정을 짤 수 있어요.", "데이 캔 세트 데어 오운 스케줄"),
    ("158. They can have more freedom.", "훨씬 더 자유롭고 자율적인 생활이 가능해요.", "데이 캔 해브 모어 프리덤"),
    ("159. They can get information and share it with other people.", "정보를 제때 수집해서 사람들에게 널리 공유할 수 있죠.", "데이 캔 겟 인포메이션 앤드 셰어 잇 위드 어더 피플"),
    ("160. It feels more like a family.", "서로 가족처럼 끈끈하고 화목한 분위기예요.", "잇 필스 모어 라이크 어 패밀리"),
    ("161. They can get a lot of useful information on the internet.", "인터넷 바다에서 생활 꿀팁들을 대량으로 건질 수 있어요.", "데이 캔 겟 어 랏 오브 유스풀 인포메이션 온 더 인터넷"),
    ("162. They can get a lot of latest information on the internet.", "인터넷으로 실시간 따끈따끈한 최신 트렌드를 빠르게 접할 수 있죠.", "데이 캔 겟 어 랏 오브 레이티스트 인포메이션 온 더 인터넷"),
    ("163. It's faster and more convenient.", "속도도 빠른 데다 이용하기가 월등히 편해요.", "잇스 패스터 앤드 모어 컨비니언트"),
    ("164. There is a lot of inaccurate information on the internet, so it's not reliable.", "인터넷엔 찌라시나 가짜 뉴스도 천지라 무턱대고 신뢰할 순 없어요.", "데어 이즈 어 랏 오브 인애큐릿 인포메이션 온 더 인터넷, 쏘 잇스 낫 리라이어블"),
    ("165. It is very distracting for workers, so they can't focus on their work.", "직원들의 주의를 딴 데로 돌려서 일에 집중을 못 하게 만들어요.", "잇 이즈 베리 디스트랙팅 포 워커스, 쏘 데이 캔트 포커스 온 데어 워크"),
    ("166. I can get responses right away.", "답장이 칼같이 와서 즉각 피드백을 받을 수 있어요.", "아이 캔 겟 리스폰시스 라이트 어웨이"),
    ("167. I can understand the speaker's feeling more accurately.", "말하는 사람의 뉘앙스나 속마음을 정확하게 읽어낼 수 있죠.", "아이 캔 언더스탠드 더 스피커스 필링 모어 애큐릿리"),
    ("168. They can create a friendly work atmosphere.", "근무 분위기를 화기애애하게 조율해 줘요.", "데이 캔 크리에이트 어 프렌들리 워크 애트모스피어"),
    ("169. They can communicate with others better.", "상대방과 대화나 소통을 훨씬 매끄럽게 풀어내죠.", "데이 캔 커뮤니케이트 위드 어더스 베터"),
    ("170. They can be good team players and make good relationships with others.", "팀워크에 강하고 사람들과 대인관계를 원만하게 잘 다져요.", "데이 캔 비 굿 팀 플레이어스 앤드 메이크 굿 리레이션십스 위드 어더스"),
    ("171. They can have a good reputation.", "주변 평판이나 이미지 관리가 훌륭해지죠.", "데이 캔 해브 어 굿 레퓨테이션"),
    ("172. They can be very influential.", "남들에게 긍정적인 영향력을 미치는 인물이 될 수 있어요.", "데이 캔 비 베리 인플루엔셜"),
    ("173. They can motivate others.", "사람들에게 동기부여와 의욕을 불어넣어 줄 수 있죠.", "데이 캔 모티베이트 어더스"),
    ("174. Everything is always changing and there is a lot of competition.", "세상은 늘 급변하고 약육강식처럼 경쟁이 치열하니까요.", "에브리씽 이즈 올웨이즈 체인지잉 앤드 데어 이즈 어 랏 오브 컴페티션"),
    ("175. They face a lot of challenges and difficulties.", "산전수전 온갖 풍파와 시련을 마주하게 돼요.", "데이 페이스 어 랏 오브 챌린지스 앤드 디피컬티스"),
    ("176. He is able to handle a variety of situations due to his confidence.", "자신감이 넘쳐서 어떤 난관이나 돌발 상황도 척척 대처해 내죠.", "히 이즈 에이블 투 핸들 어 버라이어티 오브 시추에이션스 두 투 히즈 콘피던스"),
    ("177. They have a lot of experience.", "내공이 깊고 임상/실무 경험이 풍부해요.", "데이 해브 어 랏 오브 익스피리언스"),
    ("178. They have a lot of knowledge.", "아는 게 정말 많고 박학다식해요.", "데이 해브 어 랏 오브 날리지"),
    ("179. Employees can work more efficiently and productively.", "직원들이 능률적이고 효율성 높게 일할 수 있죠.", "임플로이이즈 캔 워크 모어 이피션틀리 앤드 프로덕티블리"),
    ("180. Employees can be more satisfied with their jobs.", "직원들의 직무 만족도가 대폭 상승할 거예요.", "임플로이이즈 캔 비 모어 새티스파이드 위드 데어 잡스"),
    ("181. It can make a better work environment.", "일하고 싶게 만드는 최상의 근무 환경을 만들어 줍니다.", "잇 캔 메이크 어 베터 워크 엔바이런먼트"),
    ("182. They might appear less professional.", "자칫 어설프거나 전문성이 부족해 보일 수 있어요.", "데이 마이트 어피어 레스 프로페셔널"),
    ("183. Customers will feel satisfied and remain loyal.", "손님들이 흡족해해서 충성 단골이 될 거예요.", "커스토머스 윌 필 새티스파이드 앤드 리메인 로열"),
    ("184. It will attract more customers.", "손님 발길을 끌어모으는 데 제격이죠.", "잇 윌 어트랙트 모어 커스토머스"),
    ("185. The business will be more successful.", "사업이 대성공을 거두게(대박 나게) 될 거예요.", "더 비즈니스 윌 비 모어 서섹스풀"),
    ("186. People frequently use social media, so it will be very effective.", "요즘 다들 SNS 끼고 사니까 바이럴 효과가 직빵일 거예요.", "피플 프릭퀀틀리 유즈 소셜 미디어, 쏘 잇 윌 비 베리 이펙티브"),
    ("187. It is good for their health.", "건강에 효자 노릇을 하죠 (몸에 보약이에요).", "잇 이즈 굿 포 데어 헬스")
]

lines = []
for eng, kor, pron in items:
    lines.append(eng)
    lines.append(kor)
    lines.append(pron)
    lines.append("")

content = "\n".join(lines)

with open("d:/anti_py/trans.md", "w", encoding="utf-8") as f:
    f.write(content)

print(f"Successfully generated trans.md with {len(items)} items ({len(lines)} lines).")
